### ISSUE TITLE
Error on running from Visual studio

### ISSUE THREAD

**Issue by riverstore** [MarkVSullivan/SobekCM-Web-Application#11]
Hi! On hit F5 in VS I got this error message. Do I missing some config? Please help me. Thanks a lot.

Inner Message

    Object reference not set to an instance of an object.

Stack Trace

    at SobekCM.SobekCM_Page_Globals..ctor(Boolean isPostBack, String page_name) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM_Page_Globals.cs:line 103

SobekCM Tracer

    MILLISECOND   	CLASS.METHOD	MESSAGE
    0	sobekcm_page_globals.constructor	
    1069	sobekcm_traced_exception.constructor	Exception caught and bundled in the custom traced exception
    1075	sobekcm(.aspx).page_load

**Comment by MarkVSullivan** [comment]
Under the config subfolder, you will find a sobekcm.config file (perhaps)
and a sobekcm_config.template.

You need to update the database information there, first and foremost.  The
final file should be named sobekcm.config.

You will need to close and reopen Visual Studio after you make that change
most likely.

Mark

**Comment by riverstore** [comment]
Hi! Thanks for quick reply. I completed that step but still that error. I also download the installer, run setup and copy sobekcm.config to the project but no help.

Please help me. Thanks a lot.

**Comment by MarkVSullivan** [comment]
I think some temporary code inserted for UF is actually causing the problem.

Try replacing the current code block at SobekCM_Page_Globals (within the
main SobekCM project) at lines 102-107 with the following:

// (TEMPORARY FOR UF)
if ((
!String.IsNullOrEmpty(UI_ApplicationCache_Gateway.Settings.System_Abbreviation))
&& (
UI_ApplicationCache_Gateway.Settings.System_Abbreviation.IndexOf("UFDC") ==
0))
{
    string baseDir = System.Web.HttpContext.Current.Server.MapPath("~");
    UI_ApplicationCache_Gateway.Settings.Base_Directory = baseDir;
 }

**Comment by riverstore** [comment]
Thanks. now I got this error message

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=SobekCM
  StackTrace:
       at SobekCM.SobekCM.Write_Page_Title() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx.cs:line 154
       at ASP.sobekcm_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx:line 5
       at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
       at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
       at System.Web.UI.Page.Render(HtmlTextWriter writer)
       at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException:

**Comment by MarkVSullivan** [comment]
Okay I think the real problem is that it is not pulling the data from the
database, but I could be wrong.

I will send you the new SQL script in just a little bit.  It will be
packaged up with the new MSI this weekend, and that may help.

You can also verify this by putting a breakpoint around line 63 on
InstanceWide_Settings_Builder.cs in the SobekCM_Engine_Library.  Step
through there and I think you will see an error of some sort rather quickly.

Mark

**Comment by riverstore** [comment]
Hi! On tracing, I got this exception

System.IO.DirectoryNotFoundException was caught
  HResult=-2147024893
  Message=Could not find a part of the path 'G:\code\CSharp\SobekCM-Web-Application-master\SobekCM\design\skins\SOBEK\html'.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileSystemEnumerableIterator`1.CommonInit()
       at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
       at System.IO.Directory.GetFiles(String path, String searchPattern)
       at SobekCM.Engine_Library.Skins.Web_Skin_Utilities.Build_Skin_Complete(DataRow Skin_Row) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM_Engine_Library\Skins\Web_Skin_Utilities.cs:line 81
       at SobekCM.Engine_Library.Skins.Web_Skin_Utilities.Build_Skin(DataRow Skin_Row, String Language_Code) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM_Engine_Library\Skins\Web_Skin_Utilities.cs:line 281
       at SobekCM.Library.SobekCM_Assistant.Get_HTML_Skin(String Web_Skin_Code, SobekCM_Navigation_Object Current_Mode, Web_Skin_Collection Skin_Collection, Boolean Cache_On_Build, Custom_Tracer Tracer) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM_Library\SobekCM_Assistant.cs:line 1851
       at SobekCM.SobekCM_Page_Globals.Set_Main_Writer() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM_Page_Globals.cs:line 982
       at SobekCM.SobekCM_Page_Globals.On_Page_Load() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM_Page_Globals.cs:line 945
       at SobekCM.SobekCM.Page_Load(Object Sender, EventArgs E) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx.cs:line 34
  InnerException:

**Comment by MarkVSullivan** [comment]
Ah.. Okay.  Give me a day or so.  I will test out a new instance running it
on a machine from scratch, and make some notes.

I will probably end up pushing out a new version to fix the couple issues
that pop-up.  (For example, the lack of that directory really shouldn't
cause the system to go ape.)

Mark

**Comment by riverstore** [comment]
Hi! Thanks a lot. I'd like to report some other problems on "installed version" (I run from code to debug that problem).

- When a new user registered, the system don't create the folder "\wwwroot\mysobek\InProcess\<username>\newgroup\" so it cause error when creating new item. I create that folders manually and the problem was solve

- When create new item with DLOC template, it show a white page without any error message when hit Accept
- When create new item with Internal template, hit Next and it show the white page

Regard.

**Comment by MarkVSullivan** [comment]
Awesome, thanks!!

**Comment by riverstore** [comment]
Hi! Does the latest commit solve the problems? I run it and got this error

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=SobekCM
  StackTrace:
       at SobekCM.SobekCM.Write_Page_Title() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx.cs:line 154
       at ASP.sobekcm_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx:line 5
       at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
       at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
       at System.Web.UI.Page.Render(HtmlTextWriter writer)
       at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException:

**Comment by MarkVSullivan** [comment]
Did you copy over your design files from your instance of SobekCM under the
Visual Studio instance?

Mark

**Comment by riverstore** [comment]
Hi! Can you please give me more information about this. I copied files from the design folder from the installed version to the project but no help. Thanks a lot.

**Comment by rbernardy** [comment]
Instead of copying files I recommend you consider using mklink (run as administrator) to make symbolic links to the 'live' directories from the SobeCM dev dir. I use this method so I don't have to copy files (I maintain a complete local sync of our live site). That way I can debug within VS and also serve the site up normally via IIS.

**Comment by MarkVSullivan** [comment]
Interesting idea Richard!  I will have to look at that as well.

**Comment by MarkVSullivan** [comment]
I am about to release the new installer.  Then, we should start with that,
the latest version, and I expect it will work better for you.

After I release that installer, I will also test and add instructions on
how to debug within Visual Studio, but you seem to be doing all the right
things.

Mark


On Fri, Apr 10, 2015 at 10:02 AM, Richard Bernardy <notifications@github.com

**Comment by riverstore** [comment]
I'm waiting for you :)

**Comment by MarkVSullivan** [comment]
The new installer is here:  http://sobekdigital.com/tools/sobekcm_x64.msi .


I will roll it out more officially later today hopefully, when I get chance
to digitally sign the installer.  But, you can take a look at it from that
link now.


It installs the latest version, the builder, and solr/lucene.   It also
installs the scheduled task for the builder to run.

I will also start testing with what steps need to be done to debug from the
current code in Visual Studio.

Mark

**Comment by riverstore** [comment]
Thanks a lot for your hard work.

**Comment by MarkVSullivan** [comment]
Is this now working for you?

Mark

**Comment by riverstore** [comment]
Hi! Sorry for long response. I'm busy at my work. Just get the latest commit. I got this error

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=SobekCM
  StackTrace:
       at SobekCM.SobekCM.Write_Page_Title() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx.cs:line 154
       at ASP.sobekcm_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx:line 5
       at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
       at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
       at System.Web.UI.Page.Render(HtmlTextWriter writer)
       at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException: 

PS: I also copied the design folder from installed folder but still error. Thanks

**Comment by riverstore** [comment]
Hi! I just download the latest commit and it work fine but on trying to create a new item with Internal template, I got error message "No Institution Code". I filled all fields.

Please help me. Thanks a lot.

**Comment by MarkVSullivan** [comment]
That just means you need to set the source institution in that template.
It is not set by default.

That should be one of the elements you can enter there.

You may want to add an 'Institution' type aggregation for your institution,
if there is not one added already.

Mark

**Comment by riverstore** [comment]
Thanks a lot. Can you please tell me the file(s) to edit. Thanks again.

**Comment by MarkVSullivan** [comment]
Oh, let me explain this better.

While you are trying to submit the material online using the internal
header, one of the options provided for you as you enter the information
about the item is Source Institution.  Just be sure to select an option in
that dropdown.  Are there some options listed there?

Mark

**Comment by riverstore** [comment]
Thanks. The combo in "Holding Location" , "Source Institution" are empty. Do I miss something?

**Comment by MarkVSullivan** [comment]
Go to the system admin menu, add use the Add New Collection Wizard to a new
aggregation of type INSTITUTION.

Then, that can be set as the source and holding.

I think the new installer does that, but I will have to double check it I
guess.

Mark

**Comment by riverstore** [comment]
Hi! Sorry but it's still empty, I build from source code not install from the installer.

**Comment by MarkVSullivan** [comment]
Hmm.. try resetting the cache, or stopping and restarting Visual Studio.
Let me know if that works.

It *should* appear in there immediately.

Are you logged on as the system admin trying to add through the
built-in *internal
*sample template?

If your site is available on the web, shoot me an email at
Mark.V.Sullivan@gmail.com, and I can register with it and take a look at it.

Mark

**Comment by MarkVSullivan** [comment]
Oh, yes.. just confirmed the same thing you saw.  I reset the cache and
then the institution popped in.  I think the template is cached for several
minutes and the lack of institution is cached with it.  I will have to look
at clearing that and ensuring you don't need to reset the cache in the
future like this.

mark

**Comment by riverstore** [comment]
Hi! I restart Visual studio and it working now. But I found a new problem is that it doesnt support Unicode. The text in the black eclipse should be "THPT Lấp Vò 3" (ấ and ò was replaced by ?)

http://i.imgur.com/0zdOXsI.png

**Comment by riverstore** [comment]
It show like as I told above (Unicode characters was replaced by ?)

**Comment by MarkVSullivan** [comment]
Oh, I see it!  The database actually does support Unicode for those values,
but it looks like the SobekCM_Save_Item_Aggregation stored procedure itself
normalizes to non-Unicode.

Thank you for pointing that out!

If you are comfortable in SQL, you can run the script below. It will be
included in the next version.


-- Stored procedure to save the basic item aggregation information
ALTER PROCEDURE [dbo].[SobekCM_Save_Item_Aggregation]
@aggregationid int,
@code varchar(20),
@name nvarchar(255),
@shortname nvarchar(100),
@description nvarchar(1000),
@thematicHeadingId int,
@type varchar(50),
@isactive bit,
@hidden bit,
@display_options varchar(10),
@map_search tinyint,
@map_display tinyint,
@oai_flag bit,
@oai_metadata nvarchar(2000),
@contactemail varchar(255),
@defaultinterface varchar(10),
@externallink nvarchar(255),
@parentid int,
@username varchar(100),
@languageVariants varchar(500),
@newaggregationid int output
AS
begin transaction

-- Set flag to see if this was basically just created (either new or
undeleted)
declare @newly_added bit;
set @newly_added = 'false';

   -- If the aggregation id is less than 1 then this is for a new
aggregation
   if ((@aggregationid  < 1 ) and (( select COUNT(*) from
SobekCM_Item_Aggregation where Code=@code ) = 0 ))
   begin

-- Insert a new row
insert into SobekCM_Item_Aggregation(Code, [Name], Shortname, Description,
ThematicHeadingID, [Type], isActive, Hidden, DisplayOptions, Map_Search,
Map_Display, OAI_Flag, OAI_Metadata, ContactEmail, HasNewItems,
DefaultInterface, External_Link, DateAdded, LanguageVariants )
values(@code, @name, @shortname, @description, @thematicHeadingId, @type,
@isActive, @hidden, @display_options, @map_search, @map_display, @oai_flag,
@oai_metadata, @contactemail, 'false', @defaultinterface, @externallink,
GETDATE(), @languageVariants );

-- Get the primary key
set @newaggregationid = @@identity;

-- insert the CREATED milestone
insert into [SobekCM_Item_Aggregation_Milestones] ( AggregationID,
Milestone, MilestoneDate, MilestoneUser )
values ( @newaggregationid, 'Created', getdate(), @username );

-- Since this was a brand new, set flag
set @newly_added='true';
   end
   else
   begin

  -- Add special code to indicate if this aggregation was undeleted
  if ( exists ( select 1 from SobekCM_Item_Aggregation where Code=@Code and
Deleted='true'))
  begin
declare @deletedid int;
set @deletedid = ( select aggregationid from SobekCM_Item_Aggregation where
Code=@Code );

-- insert the UNDELETED milestone
insert into [SobekCM_Item_Aggregation_Milestones] ( AggregationID,
Milestone, MilestoneDate, MilestoneUser )
values ( @deletedid, 'Created (undeleted as previously existed)',
getdate(), @username );

-- Since this was undeleted, let's make sure this collection isn't linked
-- to any parent collections
delete from SobekCM_Item_Aggregation_Hierarchy
where ChildID=@deletedid;

-- Since this was UNDELETED, set flag
set @newly_added='true';
  end;

      -- Update the existing row
      update SobekCM_Item_Aggregation
      set
Code = @code,
[Name] = @name,
ShortName = @shortname,
[Description] = @description,
ThematicHeadingID = @thematicHeadingID,
[Type] = @type,
isActive = @isactive,
Hidden = @hidden,
DisplayOptions = @display_options,
Map_Search = @map_search,
Map_Display = @map_display,
OAI_Flag = @oai_flag,
OAI_Metadata = @oai_metadata,
ContactEmail = @contactemail,
DefaultInterface = @defaultinterface,
External_Link = @externallink,
Deleted = 'false',
DeleteDate = null,
LanguageVariants = @languageVariants
      where AggregationID = @aggregationid or Code = @code;

      -- Set the return value to the existing id
      set @newaggregationid = ( select aggregationid from
SobekCM_Item_Aggregation where Code=@Code );

   end;

-- Was a parent id provided
if ( isnull(@parentid, -1 ) > 0 )
begin
-- Now, see if the link to the parent exists
if (( select count(*) from SobekCM_Item_Aggregation_Hierarchy H where
H.ParentID = @parentid and H.ChildID = @newaggregationid ) < 1 )
begin
insert into SobekCM_Item_Aggregation_Hierarchy ( ParentID, ChildID )
values ( @parentid, @newaggregationid );
end;

-- If this was newly added (new or undeleted), ensure permissions copied
over from parent
if ( @newly_added = 'true' )
begin
-- Add individual user permissions first
insert into mySobek_User_Edit_Aggregation ( UserID, AggregationID,
CanSelect, CanEditItems,
IsCurator, IsAdmin, CanEditMetadata, CanEditBehaviors, CanPerformQc,
CanUploadFiles, CanChangeVisibility, CanDelete )
select UserID, @newaggregationid, CanSelect, CanEditItems,
IsCurator, IsAdmin, CanEditMetadata, CanEditBehaviors, CanPerformQc,
CanUploadFiles, CanChangeVisibility, CanDelete
from mySobek_User_Edit_Aggregation A
where ( AggregationID = @parentid )
  and ( not exists ( select * from mySobek_User_Edit_Aggregation L where
L.UserID=A.UserID and L.AggregationID=@newaggregationid ))
  and (    ( CanEditMetadata='true' )
                or ( CanEditBehaviors='true' )
                or ( CanPerformQc='true' )
                or ( CanUploadFiles='true' )
                or ( CanChangeVisibility='true' )
                or ( IsCurator='true' )
                or ( IsAdmin='true' ));

-- Add user group permissions next
insert into mySobek_User_Group_Edit_Aggregation ( UserGroupID,
AggregationID, CanSelect, CanEditItems,
IsCurator, IsAdmin, CanEditMetadata, CanEditBehaviors, CanPerformQc,
CanUploadFiles, CanChangeVisibility, CanDelete )
select UserGroupID, @newaggregationid, CanSelect, CanEditItems,
IsCurator, IsAdmin, CanEditMetadata, CanEditBehaviors, CanPerformQc,
CanUploadFiles, CanChangeVisibility, CanDelete
from mySobek_User_Group_Edit_Aggregation A
where ( AggregationID = @parentid )
  and ( not exists ( select * from mySobek_User_Group_Edit_Aggregation L
where L.UserGroupID=A.UserGroupID and L.AggregationID=@newaggregationid ))
  and (    ( CanEditMetadata='true' )
                or ( CanEditBehaviors='true' )
                or ( CanPerformQc='true' )
                or ( CanUploadFiles='true' )
                or ( CanChangeVisibility='true' )
                or ( IsCurator='true' )
                or ( IsAdmin='true' ));
end;
end;

commit transaction;
GO

**Comment by riverstore** [comment]
Thanks! It's working fine now :)

**Comment by riverstore** [comment]
Hi! It's me again ^^.

I just get the latest code. when trying to run the code, I got this error message

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=SobekCM
  StackTrace:
       at SobekCM.SobekCM.Write_Page_Title() in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx.cs:line 169
       at ASP.sobekcm_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in g:\code\CSharp\SobekCM-Web-Application-master\SobekCM\SobekCM.aspx:line 5
       at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
       at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
       at System.Web.UI.Page.Render(HtmlTextWriter writer)
       at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
       at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException: 

I point to the old database (which is running fine) that error disappear, but I got this error message on the browser.

404 - INVALID URL Web skin indicated is invalid, default web skin invalid 

Please help me. Thanks a lot.

**Comment by MarkVSullivan** [comment]
Which version is the OLD database?  You can determine this by looking at
the SobekCM_Database_Version table.

So, run:

select * from SobekCM_Database_Version;

You can run all the values you get together, like 4.8.11, for example.

**Comment by riverstore** [comment]
Hi! The old version is 4.8.8
